[package]
name = "sunflower"
version = "0.1"
lean_version = "leanprover-community/lean:3.48.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "3b4e9d58eae1978db9bd73d4c5f9c90fd4bb65ee"}
